#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O eDP-1 HDMI-1

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config focused_border_color "#dee0e4"
bspc config normal_border_color "#1c1e22"
bspc config active_border_color "#a9dc76"
bspc config presel_feedback_color "#fc6a67"
# bspc config presel_feedback_opacity 100
bspc config border_width 3
bspc config borderless_monocle true

bspc config window_gap 5

bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

bspc config split_ratio 0.5

# rules
bspc rule -a feh state=floating
bspc rule -a Tk state=floating

# start resources
xrdb -merge ~/.Xresources

~/.config/polybar/launch.sh &
MONITOR=$(polybar --list-monitors | grep eDP | cut -d":" -f1) polybar --reload &

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker
pkill battery-alert; ~/.config/bin/battery-alert &

# start picom
picom --config $HOME/.config/picom/picom2.conf & 

bash $HOME/.config/bin/random_wallpaper
