live_config_reload = true
[window]
    padding = { x = 5, y = 5 }
    dynamic_padding = true
# decorations = "Full"
    opacity = 0.5
    blur = false
    dynamic_title = true

[font]
    normal = { family = "JetBrainsMono NF", style = "Regular" }
    bold = { style = "Bold" }
    italic = { style = "Italic" }
    bold_italic = { style = "BoldItalic" }
